In [13]:
import numpy as np


In [14]:
a = np.zeros((2,2,2,2))

a[0,0,:,:] = [[1,2],[3,4]]
a[0,1,:,:] = [[5,6],[7,8]]
a[1,0,:,:] = [[9,10],[11,12]]
a[1,1,:,:] = [[13,14],[15,16]]


In [20]:
a

array([[[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]]],


       [[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]])

In [15]:
kron_matrix = np.array([[1, 1], [1, 1]])
kron_result = np.zeros((2, 2, 4, 4))
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        kron_result[i,j,:,:] = np.kron(a[i,j,:,:], kron_matrix)

In [16]:
kron_result

array([[[[ 1.,  1.,  2.,  2.],
         [ 1.,  1.,  2.,  2.],
         [ 3.,  3.,  4.,  4.],
         [ 3.,  3.,  4.,  4.]],

        [[ 5.,  5.,  6.,  6.],
         [ 5.,  5.,  6.,  6.],
         [ 7.,  7.,  8.,  8.],
         [ 7.,  7.,  8.,  8.]]],


       [[[ 9.,  9., 10., 10.],
         [ 9.,  9., 10., 10.],
         [11., 11., 12., 12.],
         [11., 11., 12., 12.]],

        [[13., 13., 14., 14.],
         [13., 13., 14., 14.],
         [15., 15., 16., 16.],
         [15., 15., 16., 16.]]]])

In [17]:
kron_result.shape

(2, 2, 4, 4)

In [18]:

reshaped_result = kron_result.reshape(2, 2, 1, 4, 4)
duplicated_correctly = np.repeat(reshaped_result, 2, axis=2)
final_result = duplicated_correctly.reshape(2, 4, 4, 4)

final_result


array([[[[ 1.,  1.,  2.,  2.],
         [ 1.,  1.,  2.,  2.],
         [ 3.,  3.,  4.,  4.],
         [ 3.,  3.,  4.,  4.]],

        [[ 1.,  1.,  2.,  2.],
         [ 1.,  1.,  2.,  2.],
         [ 3.,  3.,  4.,  4.],
         [ 3.,  3.,  4.,  4.]],

        [[ 5.,  5.,  6.,  6.],
         [ 5.,  5.,  6.,  6.],
         [ 7.,  7.,  8.,  8.],
         [ 7.,  7.,  8.,  8.]],

        [[ 5.,  5.,  6.,  6.],
         [ 5.,  5.,  6.,  6.],
         [ 7.,  7.,  8.,  8.],
         [ 7.,  7.,  8.,  8.]]],


       [[[ 9.,  9., 10., 10.],
         [ 9.,  9., 10., 10.],
         [11., 11., 12., 12.],
         [11., 11., 12., 12.]],

        [[ 9.,  9., 10., 10.],
         [ 9.,  9., 10., 10.],
         [11., 11., 12., 12.],
         [11., 11., 12., 12.]],

        [[13., 13., 14., 14.],
         [13., 13., 14., 14.],
         [15., 15., 16., 16.],
         [15., 15., 16., 16.]],

        [[13., 13., 14., 14.],
         [13., 13., 14., 14.],
         [15., 15., 16., 16.],
         [15., 15., 16.

In [19]:


B = np.repeat(final_result, 2, axis=0)

B.shape, B




((4, 4, 4, 4),
 array([[[[ 1.,  1.,  2.,  2.],
          [ 1.,  1.,  2.,  2.],
          [ 3.,  3.,  4.,  4.],
          [ 3.,  3.,  4.,  4.]],
 
         [[ 1.,  1.,  2.,  2.],
          [ 1.,  1.,  2.,  2.],
          [ 3.,  3.,  4.,  4.],
          [ 3.,  3.,  4.,  4.]],
 
         [[ 5.,  5.,  6.,  6.],
          [ 5.,  5.,  6.,  6.],
          [ 7.,  7.,  8.,  8.],
          [ 7.,  7.,  8.,  8.]],
 
         [[ 5.,  5.,  6.,  6.],
          [ 5.,  5.,  6.,  6.],
          [ 7.,  7.,  8.,  8.],
          [ 7.,  7.,  8.,  8.]]],
 
 
        [[[ 1.,  1.,  2.,  2.],
          [ 1.,  1.,  2.,  2.],
          [ 3.,  3.,  4.,  4.],
          [ 3.,  3.,  4.,  4.]],
 
         [[ 1.,  1.,  2.,  2.],
          [ 1.,  1.,  2.,  2.],
          [ 3.,  3.,  4.,  4.],
          [ 3.,  3.,  4.,  4.]],
 
         [[ 5.,  5.,  6.,  6.],
          [ 5.,  5.,  6.,  6.],
          [ 7.,  7.,  8.,  8.],
          [ 7.,  7.,  8.,  8.]],
 
         [[ 5.,  5.,  6.,  6.],
          [ 5.,  5.,  6.,  6.],
 